server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/no_teacher?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
    redis:
      time-to-live: 600s
      key-prefix: mail_cache_
  redis:
    host: 192.168.48.158
    port: 6379
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最佳连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000


