server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
    redis:
      time-to-live: 60s
      key-prefix: mail_cache_
  redis:
    host: 192.168.48.158
    port: 6379
    password: 123456
