server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/no_teacher?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: word-service
  cloud:
    nacos:
      config:
        server-addr: 192.168.48.158:8848
      discovery:
        server-addr: 192.168.48.158:8848





mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最佳连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000



